version: '3'
services:
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    links:
      - redis
    networks:
      - bldyrnet
    restart:
      always

  pc-builds:
    build:
      context: ./services/pc-builds
      dockerfile: Dockerfile
    links:
      - redis
    networks:
      - bldyrnet
    restart:
      always

  redis:
    image: redis
    networks:
      - bldyrnet

  db:
    image: postgres
    networks:
      - bldyrnet

networks:
  bldyrnet:
