version: '3'
services:
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    links:
      - redis
    networks:
      - default
    restart:
      always

  pc-builds:
    build:
      context: ./services/pc-builds
      dockerfile: Dockerfile
    links:
      - redis
    networks:
      - default
    restart:
      always

  redis:
    image: redis

  postgres:
    image: postgres:latest

networks:
  default:
