version: '3'
services:
  api-gateway:
    image: api-gateway:0.0.1
    ports:
      - "8080:5000"
    environment:
      - NODE_ENV=production
    command: npm run start

  pc-builds:
    image: pc-builds:0.0.1
    ports:
      - "8081:5011"
    environment:
      - NODE_ENV=production
    command: npm run start

  redis:
    ports:
      - "6379:6379"

  postgres:
    ports:
      - 5432:5432
