version: '3'
services:
  api-gateway:
    image: api-gateway:0.0.1
    ports:
      - "80:5000"
    environment:
      - NODE_ENV=production
    command: npm run start
    depends_on:
      - db

  pc-builds:
    image: pc-builds:0.0.1
    ports:
      - "5011:5011"
    environment:
      - NODE_ENV=production
    command: npm run start
    depends_on:
      - db

  redis:
    ports:
      - "6379:6379"

  db:
    ports:
      - 5432:5432
