version: '3'
services:
  api-gateway:
    volumes:
      - ./services/api-gateway:/usr/src/api-gateway
    ports:
      - "5000:5000"
    environment:
      - DEBUG=test
      - NODE_ENV=development

  pc-builds:
    volumes:
      - ./services/pc-builds:/usr/src/pc-builds
    ports:
      - "5011:5011"
    environment:
      - DEBUG=test
      - NODE_ENV=development

  redis:
    ports:
      - "6379:6379"

  db:
    image: postgres
    environment:
      POSTGRES_USR: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bldyr-dev
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
